package:
  name: ghost-tree
  version: "TODO"

source:
  git_url: https://github.com/JTFouquier/ghost-tree.git

build:
  number: 0

requirements:
  build:
    - python 3.*
    - setuptools
    - numpy
    - pip
    - click >=4.0
    - nose

  run:
    - python 3.*
    - fasttree
    - muscle
    - sumaclust
    - pip
    - click >=4.0
    - nose

channels:
  - bioconda
  - conda-forge

test:
  commands:
    - ghost-tree --help

about:
  home: TODO
  license: BSD license
