package:
  name: ghost-tree
  version: "0.0.1.dev0"

source:
  git_url: https://github.com/JTFouquier/ghost-tree.git

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python 3.5
    - setuptools

  run:
    - python 3.5
    - fasttree
    - muscle
    - sumaclust
    - click >=4.0
    - scikit-bio >=0.5.1
    - numpy
    - nose

test:
  commands:
    - ghost-tree --help
    - nosetests -v ghosttree

about:
  home: https://github.com/JTFouquier/ghost-tree
  license: BSD license
  summary: ghost-tree is a bioinformatics tool that combines sequence data from two genetic marker databases into one phylogenetic tree that can be used for diversity analyses.